/** UUIDs are opaque identifiers generated by the client or assigned by Auth. */
export type Uuid = string;

/** Audit fields controlled by the server for every remote entity. */
export type EntityTimestamps = {
  createdAt: string;
  updatedAt: string;
};

/** Metadata persisted remotely and used for optimistic concurrency. */
export type RemoteEntity = EntityTimestamps & {
  id: Uuid;
  version: number;
};

/** Device-only state. It must never be sent as part of a remote entity. */
export type SyncStatus = "local" | "pending" | "syncing" | "synced" | "error";

export type LocalEntityMetadata = {
  ownerUserId: Uuid;
  localRevision: number;
  baseVersion: number | null;
  syncStatus: SyncStatus;
  localUpdatedAt: string;
  remoteSnapshot?: unknown;
};

export type DomainValidationIssue = {
  path: string;
  message: string;
};

export class DomainValidationError extends Error {
  readonly issues: readonly DomainValidationIssue[];

  constructor(issues: readonly DomainValidationIssue[]) {
    super(issues.map((issue) => `${issue.path} ${issue.message}`).join("; "));
    this.name = "DomainValidationError";
    this.issues = issues;
  }
}

export function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function expectRecord(value: unknown, path: string): Record<string, unknown> {
  if (!isRecord(value)) {
    throw new DomainValidationError([{ path, message: "must be an object" }]);
  }

  return value;
}

export function expectOnlyKeys(value: Record<string, unknown>, allowed: readonly string[], path: string) {
  const unexpected = Object.keys(value).filter((key) => !allowed.includes(key));
  if (unexpected.length > 0) {
    throw new DomainValidationError(unexpected.map((key) => ({ path: `${path}.${key}`, message: "is not allowed" })));
  }
}

export function expectUuid(value: unknown, path: string): Uuid {
  if (typeof value !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) {
    throw new DomainValidationError([{ path, message: "must be a UUID" }]);
  }

  return value;
}

export function expectIsoDate(value: unknown, path: string): string {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    throw new DomainValidationError([{ path, message: "must be an ISO calendar date" }]);
  }

  const [year, month, day] = value.split("-").map(Number);
  const parsed = new Date(Date.UTC(year, month - 1, day));
  if (parsed.getUTCFullYear() !== year || parsed.getUTCMonth() !== month - 1 || parsed.getUTCDate() !== day) {
    throw new DomainValidationError([{ path, message: "must be a real calendar date" }]);
  }

  return value;
}

export function expectString(value: unknown, path: string, options: { min?: number; max: number; trim?: boolean }): string {
  if (typeof value !== "string") {
    throw new DomainValidationError([{ path, message: "must be a string" }]);
  }

  const comparable = options.trim ? value.trim() : value;
  if ((options.min !== undefined && comparable.length < options.min) || comparable.length > options.max) {
    throw new DomainValidationError([{ path, message: `must contain between ${options.min ?? 0} and ${options.max} characters` }]);
  }

  return value;
}

export function expectPositiveInteger(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 1) {
    throw new DomainValidationError([{ path, message: "must be a positive integer" }]);
  }

  return value;
}
