import type { NextRequest } from "next/server";
import { apiError, privateJson } from "@/lib/auth/http";
import { authorizeRequest } from "@/lib/auth/guards";
import { findVisibleInspection, InspectionReadError } from "@/lib/repositories/inspections";
import { createRequestSupabaseClient } from "@/lib/supabase/server";
import { runInspectionMutation } from "@/lib/api/inspection-http";

export const dynamic = "force-dynamic";

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  const auth = createRequestSupabaseClient(request);
  const permission = await authorizeRequest(auth.client, ["technician", "coordinator"]);
  if ("error" in permission) return auth.withCookies(apiError(permission.error === 401 ? "UNAUTHENTICATED" : "FORBIDDEN"));
  try {
    const detail = await findVisibleInspection(auth.client, params.id);
    return auth.withCookies(detail ? privateJson(detail) : apiError("NOT_FOUND"));
  } catch (error) {
    if (!(error instanceof InspectionReadError)) throw error;
    return auth.withCookies(apiError("UNAVAILABLE"));
  }
}

/** PUT creates the inspection; the id is generated by the client and passed in the path. */
export async function PUT(request: NextRequest, { params }: { params: { id: string } }) {
  const auth = createRequestSupabaseClient(request);
  return (await runInspectionMutation(request, auth, params.id, "inspection.create")).response;
}

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  const auth = createRequestSupabaseClient(request);
  return (await runInspectionMutation(request, auth, params.id, "inspection.update")).response;
}

/** DELETE discards a draft; replaying the same Idempotency-Key returns the stored ACK. */
export async function DELETE(request: NextRequest, { params }: { params: { id: string } }) {
  const auth = createRequestSupabaseClient(request);
  return (await runInspectionMutation(request, auth, params.id, "inspection.discard")).response;
}